### PR TITLE
Sidecar: add timeout on writer operations

### PR DESCRIPTION
**Pull request by lferran**
### Description
Describe the proposed changes made in this PR.

### How was this PR tested?
Describe how you tested this PR.

### CODE REVIEW

**Comment by lferran** [comment]
> What happens if a setresource is > 3 min ?

@bloodbare in that case, the writer grpc client at the sidecar will timeout and the sidecar will retry it later on.

3 min was my initia proposal, but do you think the timeout should be bigger? Like.. 10 Minutes? At max it should be set to the nats timeout.

Right now I feel we don't have enough data to set an approrpiate value.

Which makes me think... we could add metrics on node operations.

**Comment by vangheem** [comment]
We can start with no timeout(maybe with `-1` default setting) and make sure to get metrics on it before we enforce anything.

**Comment by bloodbare** [comment]
Agreee with nathan , also we have metrics on jaegger

**Comment by bloodbare** [comment]
As the bug has been fixed, we will pospone this PR until node refactor.

**Pull request closed without merging**
